export interface QuranSurahMeta {
  id: number;
  name: string;
  englishName: string;
  englishTranslation: string;
  makkia: 1 | 0; // 1 = Makki, 0 = Madani
  ayahCount: number;
  startPage: number;
  endPage: number;
}

export const QURAN_SURAHS: QuranSurahMeta[] = [
  { id: 1, name: "الفاتحة", englishName: "Al-Fatihah", englishTranslation: "The Opening", makkia: 1, ayahCount: 7, startPage: 1, endPage: 1 },
  { id: 2, name: "البقرة", englishName: "Al-Baqarah", englishTranslation: "The Cow", makkia: 0, ayahCount: 286, startPage: 2, endPage: 49 },
  { id: 3, name: "آل عمران", englishName: "Ali 'Imran", englishTranslation: "Family of Imran", makkia: 0, ayahCount: 200, startPage: 50, endPage: 76 },
  { id: 4, name: "النساء", englishName: "An-Nisa", englishTranslation: "The Women", makkia: 0, ayahCount: 176, startPage: 77, endPage: 106 },
  { id: 5, name: "المائدة", englishName: "Al-Ma'idah", englishTranslation: "The Table Spread", makkia: 0, ayahCount: 120, startPage: 106, endPage: 127 },
  { id: 6, name: "الأنعام", englishName: "Al-An'am", englishTranslation: "The Cattle", makkia: 1, ayahCount: 165, startPage: 128, endPage: 150 },
  { id: 7, name: "الأعراف", englishName: "Al-A'raf", englishTranslation: "The Heights", makkia: 1, ayahCount: 206, startPage: 151, endPage: 176 },
  { id: 8, name: "الأنفال", englishName: "Al-Anfal", englishTranslation: "The Spoils of War", makkia: 0, ayahCount: 75, startPage: 177, endPage: 186 },
  { id: 9, name: "التوبة", englishName: "At-Tawbah", englishTranslation: "The Repentance", makkia: 0, ayahCount: 129, startPage: 187, endPage: 207 },
  { id: 10, name: "يونس", englishName: "Yunus", englishTranslation: "Jonah", makkia: 1, ayahCount: 109, startPage: 208, endPage: 221 },
  { id: 11, name: "هود", englishName: "Hud", englishTranslation: "Hud", makkia: 1, ayahCount: 123, startPage: 221, endPage: 235 },
  { id: 12, name: "يوسف", englishName: "Yusuf", englishTranslation: "Joseph", makkia: 1, ayahCount: 111, startPage: 235, endPage: 248 },
  { id: 13, name: "الرعد", englishName: "Ar-Ra'd", englishTranslation: "The Thunder", makkia: 0, ayahCount: 43, startPage: 249, endPage: 255 },
  { id: 14, name: "إبراهيم", englishName: "Ibrahim", englishTranslation: "Abraham", makkia: 1, ayahCount: 52, startPage: 255, endPage: 261 },
  { id: 15, name: "الحجر", englishName: "Al-Hijr", englishTranslation: "The Rocky Tract", makkia: 1, ayahCount: 99, startPage: 262, endPage: 267 },
  { id: 16, name: "النحل", englishName: "An-Nahl", englishTranslation: "The Bee", makkia: 1, ayahCount: 128, startPage: 267, endPage: 281 },
  { id: 17, name: "الإسراء", englishName: "Al-Isra", englishTranslation: "The Night Journey", makkia: 1, ayahCount: 111, startPage: 282, endPage: 293 },
  { id: 18, name: "الكهف", englishName: "Al-Kahf", englishTranslation: "The Cave", makkia: 1, ayahCount: 110, startPage: 293, endPage: 304 },
  { id: 19, name: "مريم", englishName: "Maryam", englishTranslation: "Mary", makkia: 1, ayahCount: 98, startPage: 305, endPage: 312 },
  { id: 20, name: "طه", englishName: "Taha", englishTranslation: "Ta-Ha", makkia: 1, ayahCount: 135, startPage: 312, endPage: 321 },
  { id: 21, name: "الأنبياء", englishName: "Al-Anbiya", englishTranslation: "The Prophets", makkia: 1, ayahCount: 112, startPage: 322, endPage: 331 },
  { id: 22, name: "الحج", englishName: "Al-Hajj", englishTranslation: "The Pilgrimage", makkia: 0, ayahCount: 78, startPage: 332, endPage: 341 },
  { id: 23, name: "المؤمنون", englishName: "Al-Mu'minun", englishTranslation: "The Believers", makkia: 1, ayahCount: 118, startPage: 342, endPage: 349 },
  { id: 24, name: "النور", englishName: "An-Nur", englishTranslation: "The Light", makkia: 0, ayahCount: 64, startPage: 350, endPage: 359 },
  { id: 25, name: "الفرقان", englishName: "Al-Furqan", englishTranslation: "The Criterion", makkia: 1, ayahCount: 77, startPage: 359, endPage: 366 },
  { id: 26, name: "الشعراء", englishName: "Ash-Shu'ara", englishTranslation: "The Poets", makkia: 1, ayahCount: 227, startPage: 367, endPage: 376 },
  { id: 27, name: "النمل", englishName: "An-Naml", englishTranslation: "The Ant", makkia: 1, ayahCount: 93, startPage: 377, endPage: 385 },
  { id: 28, name: "القصص", englishName: "Al-Qasas", englishTranslation: "The Stories", makkia: 1, ayahCount: 88, startPage: 385, endPage: 396 },
  { id: 29, name: "العنكبوت", englishName: "Al-'Ankabut", englishTranslation: "The Spider", makkia: 1, ayahCount: 69, startPage: 396, endPage: 404 },
  { id: 30, name: "الروم", englishName: "Ar-Rum", englishTranslation: "The Romans", makkia: 1, ayahCount: 60, startPage: 404, endPage: 410 },
  { id: 31, name: "لقمان", englishName: "Luqman", englishTranslation: "Luqman", makkia: 1, ayahCount: 34, startPage: 411, endPage: 415 },
  { id: 32, name: "السجدة", englishName: "As-Sajdah", englishTranslation: "The Prostration", makkia: 1, ayahCount: 30, startPage: 415, endPage: 417 },
  { id: 33, name: "الأحزاب", englishName: "Al-Ahzab", englishTranslation: "The Combined Forces", makkia: 0, ayahCount: 73, startPage: 418, endPage: 427 },
  { id: 34, name: "سبأ", englishName: "Saba", englishTranslation: "Sheba", makkia: 1, ayahCount: 54, startPage: 428, endPage: 434 },
  { id: 35, name: "فاطر", englishName: "Fatir", englishTranslation: "Originator", makkia: 1, ayahCount: 45, startPage: 434, endPage: 440 },
  { id: 36, name: "يس", englishName: "Ya-Sin", englishTranslation: "Ya Sin", makkia: 1, ayahCount: 83, startPage: 440, endPage: 445 },
  { id: 37, name: "الصافات", englishName: "As-Saffat", englishTranslation: "Those who set the Ranks", makkia: 1, ayahCount: 182, startPage: 446, endPage: 452 },
  { id: 38, name: "ص", englishName: "Sad", englishTranslation: "The Letter \"Saad\"", makkia: 1, ayahCount: 88, startPage: 453, endPage: 458 },
  { id: 39, name: "الزمر", englishName: "Az-Zumar", englishTranslation: "The Troops", makkia: 1, ayahCount: 75, startPage: 458, endPage: 467 },
  { id: 40, name: "غافر", englishName: "Ghafir", englishTranslation: "The Forgiver", makkia: 1, ayahCount: 85, startPage: 467, endPage: 476 },
  { id: 41, name: "فصلت", englishName: "Fussilat", englishTranslation: "Explained in Detail", makkia: 1, ayahCount: 54, startPage: 477, endPage: 482 },
  { id: 42, name: "الشورى", englishName: "Ash-Shuraa", englishTranslation: "The Consultation", makkia: 1, ayahCount: 53, startPage: 483, endPage: 489 },
  { id: 43, name: "الزخرف", englishName: "Az-Zukhruf", englishTranslation: "The Ornaments of Gold", makkia: 1, ayahCount: 89, startPage: 489, endPage: 495 },
  { id: 44, name: "الدخان", englishName: "Ad-Dukhan", englishTranslation: "The Smoke", makkia: 1, ayahCount: 59, startPage: 496, endPage: 498 },
  { id: 45, name: "الجاثية", englishName: "Al-Jathiyah", englishTranslation: "The Crouching", makkia: 1, ayahCount: 37, startPage: 499, endPage: 502 },
  { id: 46, name: "الأحقاف", englishName: "Al-Ahqaf", englishTranslation: "The Wind-Curved Sandhills", makkia: 1, ayahCount: 35, startPage: 502, endPage: 506 },
  { id: 47, name: "محمد", englishName: "Muhammad", englishTranslation: "Muhammad", makkia: 0, ayahCount: 38, startPage: 507, endPage: 510 },
  { id: 48, name: "الفتح", englishName: "Al-Fath", englishTranslation: "The Victory", makkia: 0, ayahCount: 29, startPage: 511, endPage: 515 },
  { id: 49, name: "الحجرات", englishName: "Al-Hujurat", englishTranslation: "The Rooms", makkia: 0, ayahCount: 18, startPage: 515, endPage: 517 },
  { id: 50, name: "ق", englishName: "Qaf", englishTranslation: "The Letter \"Qaf\"", makkia: 1, ayahCount: 45, startPage: 518, endPage: 520 },
  { id: 51, name: "الذاريات", englishName: "Adh-Dhariyat", englishTranslation: "The Winnowing Winds", makkia: 1, ayahCount: 60, startPage: 520, endPage: 523 },
  { id: 52, name: "الطور", englishName: "At-Tur", englishTranslation: "The Mount", makkia: 1, ayahCount: 49, startPage: 523, endPage: 525 },
  { id: 53, name: "النجم", englishName: "An-Najm", englishTranslation: "The Star", makkia: 1, ayahCount: 62, startPage: 526, endPage: 528 },
  { id: 54, name: "القمر", englishName: "Al-Qamar", englishTranslation: "The Moon", makkia: 1, ayahCount: 55, startPage: 528, endPage: 531 },
  { id: 55, name: "الرحمن", englishName: "Ar-Rahman", englishTranslation: "The Beneficent", makkia: 0, ayahCount: 78, startPage: 531, endPage: 534 },
  { id: 56, name: "الواقعة", englishName: "Al-Waqi'ah", englishTranslation: "The Inevitable", makkia: 1, ayahCount: 96, startPage: 534, endPage: 537 },
  { id: 57, name: "الحديد", englishName: "Al-Hadid", englishTranslation: "The Iron", makkia: 0, ayahCount: 29, startPage: 537, endPage: 541 },
  { id: 58, name: "المجادلة", englishName: "Al-Mujadila", englishTranslation: "The Pleading Woman", makkia: 0, ayahCount: 22, startPage: 542, endPage: 545 },
  { id: 59, name: "الحشر", englishName: "Al-Hashr", englishTranslation: "The Exile", makkia: 0, ayahCount: 24, startPage: 545, endPage: 548 },
  { id: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", englishTranslation: "She that is to be examined", makkia: 0, ayahCount: 13, startPage: 549, endPage: 551 },
  { id: 61, name: "الصف", englishName: "As-Saf", englishTranslation: "The Ranks", makkia: 0, ayahCount: 14, startPage: 551, endPage: 553 },
  { id: 62, name: "الجمعة", englishName: "Al-Jumu'ah", englishTranslation: "The Congregation", makkia: 0, ayahCount: 11, startPage: 553, endPage: 554 },
  { id: 63, name: "المنافقون", englishName: "Al-Munafiqun", englishTranslation: "The Hypocrites", makkia: 0, ayahCount: 11, startPage: 554, endPage: 555 },
  { id: 64, name: "التغابن", englishName: "At-Taghabun", englishTranslation: "The Mutual Disillusion", makkia: 0, ayahCount: 18, startPage: 556, endPage: 557 },
  { id: 65, name: "الطلاق", englishName: "At-Talaq", englishTranslation: "The Divorce", makkia: 0, ayahCount: 12, startPage: 558, endPage: 559 },
  { id: 66, name: "التحريم", englishName: "At-Tahrim", englishTranslation: "The Prohibition", makkia: 0, ayahCount: 12, startPage: 560, endPage: 561 },
  { id: 67, name: "الملك", englishName: "Al-Mulk", englishTranslation: "The Sovereignty", makkia: 1, ayahCount: 30, startPage: 562, endPage: 564 },
  { id: 68, name: "القلم", englishName: "Al-Qalam", englishTranslation: "The Pen", makkia: 1, ayahCount: 52, startPage: 564, endPage: 566 },
  { id: 69, name: "الحاقة", englishName: "Al-Haqqah", englishTranslation: "The Reality", makkia: 1, ayahCount: 52, startPage: 566, endPage: 568 },
  { id: 70, name: "المعارج", englishName: "Al-Ma'arij", englishTranslation: "The Ascending Stairways", makkia: 1, ayahCount: 44, startPage: 568, endPage: 570 },
  { id: 71, name: "نوح", englishName: "Nuh", englishTranslation: "Noah", makkia: 1, ayahCount: 28, startPage: 570, endPage: 571 },
  { id: 72, name: "الجن", englishName: "Al-Jinn", englishTranslation: "The Jinn", makkia: 1, ayahCount: 28, startPage: 572, endPage: 573 },
  { id: 73, name: "المزمل", englishName: "Al-Muzzammil", englishTranslation: "The Enshrouded One", makkia: 1, ayahCount: 20, startPage: 574, endPage: 575 },
  { id: 74, name: "المدثر", englishName: "Al-Muddaththir", englishTranslation: "The Cloaked One", makkia: 1, ayahCount: 56, startPage: 575, endPage: 577 },
  { id: 75, name: "القيامة", englishName: "Al-Qiyamah", englishTranslation: "The Resurrection", makkia: 1, ayahCount: 40, startPage: 577, endPage: 578 },
  { id: 76, name: "الإنسان", englishName: "Al-Insan", englishTranslation: "The Human", makkia: 0, ayahCount: 31, startPage: 578, endPage: 580 },
  { id: 77, name: "المرسلات", englishName: "Al-Mursalat", englishTranslation: "The Emissaries", makkia: 1, ayahCount: 50, startPage: 580, endPage: 581 },
  { id: 78, name: "النبأ", englishName: "An-Naba", englishTranslation: "The Tidings", makkia: 1, ayahCount: 40, startPage: 582, endPage: 583 },
  { id: 79, name: "النازعات", englishName: "An-Nazi'at", englishTranslation: "Those who drag forth", makkia: 1, ayahCount: 46, startPage: 583, endPage: 584 },
  { id: 80, name: "عبس", englishName: "'Abasa", englishTranslation: "He Frowned", makkia: 1, ayahCount: 42, startPage: 585, endPage: 586 },
  { id: 81, name: "التكوير", englishName: "At-Takwir", englishTranslation: "The Overthrowing", makkia: 1, ayahCount: 29, startPage: 586, endPage: 586 },
  { id: 82, name: "الانفطار", englishName: "Al-Infitar", englishTranslation: "The Cleaving", makkia: 1, ayahCount: 19, startPage: 587, endPage: 587 },
  { id: 83, name: "المطففين", englishName: "Al-Mutaffifin", englishTranslation: "The Defrauding", makkia: 1, ayahCount: 36, startPage: 587, endPage: 589 },
  { id: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", englishTranslation: "The Splitting Open", makkia: 1, ayahCount: 25, startPage: 589, endPage: 590 },
  { id: 85, name: "البروج", englishName: "Al-Buruj", englishTranslation: "The Mansions of the Stars", makkia: 1, ayahCount: 22, startPage: 590, endPage: 590 },
  { id: 86, name: "الطارق", englishName: "At-Tariq", englishTranslation: "The Morning Star", makkia: 1, ayahCount: 17, startPage: 591, endPage: 591 },
  { id: 87, name: "الأعلى", englishName: "Al-A'la", englishTranslation: "The Most High", makkia: 1, ayahCount: 19, startPage: 591, endPage: 592 },
  { id: 88, name: "الغاشية", englishName: "Al-Ghashiyah", englishTranslation: "The Overwhelming", makkia: 1, ayahCount: 26, startPage: 592, endPage: 593 },
  { id: 89, name: "الفجر", englishName: "Al-Fajr", englishTranslation: "The Dawn", makkia: 1, ayahCount: 30, startPage: 593, endPage: 594 },
  { id: 90, name: "البلد", englishName: "Al-Balad", englishTranslation: "The City", makkia: 1, ayahCount: 20, startPage: 594, endPage: 595 },
  { id: 91, name: "الشمس", englishName: "Ash-Shams", englishTranslation: "The Sun", makkia: 1, ayahCount: 15, startPage: 595, endPage: 595 },
  { id: 92, name: "الليل", englishName: "Al-Layl", englishTranslation: "The Night", makkia: 1, ayahCount: 21, startPage: 595, endPage: 596 },
  { id: 93, name: "الضحى", englishName: "Ad-Duhaa", englishTranslation: "The Morning Hours", makkia: 1, ayahCount: 11, startPage: 596, endPage: 596 },
  { id: 94, name: "الشرح", englishName: "Ash-Sharh", englishTranslation: "The Relief", makkia: 1, ayahCount: 8, startPage: 596, endPage: 596 },
  { id: 95, name: "التين", englishName: "At-Tin", englishTranslation: "The Fig", makkia: 1, ayahCount: 8, startPage: 597, endPage: 597 },
  { id: 96, name: "العلق", englishName: "Al-'Alaq", englishTranslation: "The Clot", makkia: 1, ayahCount: 19, startPage: 597, endPage: 597 },
  { id: 97, name: "القدر", englishName: "Al-Qadr", englishTranslation: "The Power", makkia: 1, ayahCount: 5, startPage: 598, endPage: 598 },
  { id: 98, name: "البينة", englishName: "Al-Bayyinah", englishTranslation: "The Clear Proof", makkia: 0, ayahCount: 8, startPage: 598, endPage: 599 },
  { id: 99, name: "الزلزلة", englishName: "Az-Zalzalah", englishTranslation: "The Earthquake", makkia: 0, ayahCount: 8, startPage: 599, endPage: 599 },
  { id: 100, name: "العاديات", englishName: "Al-'Adiyat", englishTranslation: "The Courser", makkia: 1, ayahCount: 11, startPage: 599, endPage: 600 },
  { id: 101, name: "القارعة", englishName: "Al-Qari'ah", englishTranslation: "The Calamity", makkia: 1, ayahCount: 11, startPage: 600, endPage: 600 },
  { id: 102, name: "التكاثر", englishName: "At-Takathur", englishTranslation: "The Rivalry in world increase", makkia: 1, ayahCount: 8, startPage: 600, endPage: 600 },
  { id: 103, name: "العصر", englishName: "Al-'Asr", englishTranslation: "The Declining Day", makkia: 1, ayahCount: 3, startPage: 601, endPage: 601 },
  { id: 104, name: "الهمزة", englishName: "Al-Humazah", englishTranslation: "The Traducer", makkia: 1, ayahCount: 9, startPage: 601, endPage: 601 },
  { id: 105, name: "الفيل", englishName: "Al-Fil", englishTranslation: "The Elephant", makkia: 1, ayahCount: 5, startPage: 601, endPage: 601 },
  { id: 106, name: "قريش", englishName: "Quraysh", englishTranslation: "Quraysh", makkia: 1, ayahCount: 4, startPage: 602, endPage: 602 },
  { id: 107, name: "الماعون", englishName: "Al-Ma'un", englishTranslation: "The Small Kindnesses", makkia: 1, ayahCount: 7, startPage: 602, endPage: 602 },
  { id: 108, name: "الكوثر", englishName: "Al-Kawthar", englishTranslation: "The Abundance", makkia: 1, ayahCount: 3, startPage: 602, endPage: 602 },
  { id: 109, name: "الكافرون", englishName: "Al-Kafirun", englishTranslation: "The Disbelievers", makkia: 1, ayahCount: 6, startPage: 603, endPage: 603 },
  { id: 110, name: "النصر", englishName: "An-Nasr", englishTranslation: "The Divine Support", makkia: 0, ayahCount: 3, startPage: 603, endPage: 603 },
  { id: 111, name: "المسد", englishName: "Al-Masad", englishTranslation: "The Palm Fiber", makkia: 1, ayahCount: 5, startPage: 603, endPage: 603 },
  { id: 112, name: "الإخلاص", englishName: "Al-Ikhlas", englishTranslation: "The Sincerity", makkia: 1, ayahCount: 4, startPage: 604, endPage: 604 },
  { id: 113, name: "الفلق", englishName: "Al-Falaq", englishTranslation: "The Daybreak", makkia: 1, ayahCount: 5, startPage: 604, endPage: 604 },
  { id: 114, name: "الناس", englishName: "An-Nas", englishTranslation: "Mankind", makkia: 1, ayahCount: 6, startPage: 604, endPage: 604 }
];
